### ISSUE TITLE
cc argument in send.mail()

### ISSUE THREAD

**Issue by Mullefa** [rpremraj/mailR#14]
Is it foreseeable that in future releases the `send.mail()` function will have a `cc` argument.

(Btw - kudos for a very simple to use and useful package)

**Comment by rpremraj** [comment]
Hi! send.mail() already has a CC argument, and even BCC.

```r
send.mail(from = "sender@gmail.com",
          to = c("Recipient 1 <recipient1@gmail.com>", "recipient2@gmail.com"),
          cc = c("CC Recipient <cc.recipient@gmail.com>"),
          bcc = c("BCC Recipient <bcc.recipient@gmail.com>"),
          subject = "Subject of the email",
          body = "Body of the email",
          smtp = list(host.name = "aspmx.l.google.com", port = 25),
          authenticate = FALSE,
          send = TRUE)
```

I am glad you found mailR useful.

**Comment by Mullefa** [comment]
In the source code, I don't see them as function arguments of `send.mail()` or in the documentation of this function. What am I missing?

**Comment by rpremraj** [comment]
You're quite right. I will update the documentation to reference the parameters explicitly. Currently they are mentioned on the GitHub ReadMe page only.

Thanks for bringing this to my notice.

**Comment by Mullefa** [comment]
No probs! Cheers
