### ISSUE TITLE
 "Error in ls(envir = envir, all.names = private) :invalid 'envir' argument"

### ISSUE THREAD

**Issue by samfield** [rpremraj/mailR#15]
After running the following 

send.mail(from="x.x.x@gmail.com",
          to = "n.n@n.com",
          subject = "subject",
          body = "test",
          html = TRUE,
          smtp = list(host.name="smtp.gmail.com", port=465, user.name="x.x.x@gmail.com", passwd="", ssl=TRUE),
          authenticate = TRUE,
          send = TRUE)

I get the error: 

"Error in ls(envir = envir, all.names = private) :invalid 'envir' argument"

I run into this while trying to send from gmail or Exchange accounts.

Have you encountered the problem?

====version=======
> R.Version()
$platform
[1] "x86_64-w64-mingw32"
$arch
[1] "x86_64"
$os
[1] "mingw32"
$system
[1] "x86_64, mingw32"
$version.string
[1] "R version 3.1.2 (2014-10-31)"
=====packages=======
other attached packages:
[1] mailR_0.4.1

loaded via a namespace (and not attached):
[1] R.methodsS3_1.6.1 R.oo_1.18.0       R.utils_1.34.0    rJava_0.9-6       stringr_0.6.2    
[6] tools_3.1.2 
===================

**Comment by rpremraj** [comment]
Any chance you are working behind a proxy? If so, you would need to configure R to connect to the Internet via this server.

Could you also try setting the debug flag to True in send.mail() and share the output?

**Comment by samfield** [comment]
Not behind a proxy. 
But the chances were that I'm an ignorant idiot and didn't respect correct cryptographic protocol. 
SSL to TSL was the required change..Sorry for the bother. 
BTW thank you for providing a decent package that addresses also some enterprise quirks.

**Comment by rpremraj** [comment]
Glad to hear you resolved it.
