### ISSUE TITLE
Not working on rocker/hadleyverse:latest 

### ISSUE THREAD

**Issue by ignacio82** [rpremraj/mailR#20]
I'm trying the package using a docker image. This is what I'm running

    library(knitr)
    library(mailR)
    knit2html("my_report.Rmd", options = "")

    send.mail(from = "SOMETHING@gmail.com",
              to = c("SOMETHING@gmail.com"),
              subject = "HTML file generated using Markdown",
              body = "my_report.html",
              html = TRUE,
              inline = TRUE,
              smtp = list(host.name = "smtp.gmail.com", port = 465, user.name = "SOMETHING", passwd = "PASSWORD_SOMETHING", ssl = TRUE),
              authenticate = TRUE,
              send = TRUE)

I get the following error:

    Error in ls(envir = envir, all.names = private) : 
      invalid 'envir' argument

What am I doing wrong? 

Thanks!

**Comment by ghatfan99** [comment]
hello,

you must configure your server settings i think

regards

**Comment by rpremraj** [comment]
Have you altered the Gmail's security settings to allow third-party apps to connect?

**Comment by rpremraj** [comment]
Check: https://github.com/rpremraj/mailR/issues/8#issuecomment-60147204

**Comment by rpremraj** [comment]
No response... presuming issue resolved.
