### ISSUE TITLE
Could it be improved to support both HTML and Text msg at the same time?

### ISSUE THREAD

**Issue by RokaiSong** [rpremraj/mailR#24]
Most mail library allows you to set a HTML version msg and plain text version msg at the same time, so the mail client could parse and display the msg according to their own capability. But mailR only allows one type. This is causing a limitation when using this lib to send emails.

Could you please help to check if this could be improved? We are seeing it is hard coded here: https://github.com/rpremraj/mailR/blob/d7dcdf3d65843bdcdfe0bbed969a60f858838061/R/mailR.R#L199

Many thanks!

**Comment by rpremraj** [comment]
Good comment!

I have very limited capacity to work on this package in the next months. If you have any ideas on how this could work, I'd be happy to accept a patch from you.

**Comment by RokaiSong** [comment]
Thank you, Rahul. This is really great news!

**Comment by rpremraj** [comment]
;-)
