### ISSUE TITLE
Crashing R in R Studio

### ISSUE THREAD

**Issue by abeburnett** [rpremraj/mailR#34]
I install mailR from CRAN (with dependencies), and then I try to load it: library(mailR). It immediately crashes my R session. Thoughts? I'm running Revolution R Open 3.2.2 and R Studio 0.99.483.

Thank you!

**Comment by rpremraj** [comment]
Sorry ---- never tested mailR on Revolution R Open. Does it crash on a standard R installation as well?

**Comment by rpremraj** [comment]
Did you manage to resolve this issue?

**Comment by abeburnett** [comment]
I got it to work...can't remember what I did unfortunately!
