### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by MohammadMazraeh** [rpremraj/mailR#37]
Hi!
I get this error when I want to install the library:

-----------------------------------------------------------------------------------------------
install_github("rpremraj/mailR")
Downloading GitHub repo rpremraj/mailR@master
Installing mailR
"d:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/Mohammad/AppData/Local/Temp/RtmpM3r5Jn/devtools1a441f76dd2/rpremraj-mailR-1c62e08"  \
  --library="C:/Users/Mohammad/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'mailR' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/Mohammad/Documents/R/win-library/3.2/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Mohammad/Documents/R/win-library/3.2/mailR'
Error: Command failed (1)  

-----------------------------------------------------------------------------------------------
And here is my session info:

R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.9.1  sendmailR_1.2-1 RCurl_1.95-4.7  bitops_1.0-6    rjson_0.2.15   
[6] httr_1.0.0     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1     digest_0.6.8    R6_2.1.1        magrittr_1.5    stringi_0.5-5  
 [6] curl_0.9.3      rmarkdown_0.8.1 tools_3.2.2     stringr_1.0.0   httpuv_1.3.3   
[11] yaml_2.1.13     base64enc_0.1-3 htmltools_0.2.6 memoise_0.2.1

I have checked and the rJava.dll file exists but I don't have any Idea if it is corrupted!

Thank you

**Comment by rpremraj** [comment]
I am afraid this is a rJava issue. Have you tried installing rJava separately? And tried the suggestions on pages such as http://stackoverflow.com/questions/7019912/using-the-rjava-package-on-win7-64-bit-with-r?

**Comment by MohammadMazraeh** [comment]
Thank You!
I must have searched and didn't bother you to found it for me!
According the solutions in the link you have provided, removing Java_HOME made installation possible.
