### ISSUE TITLE
RMarkdown Chunk Name Problem: "Error in ls(envir = envir, all.names = private) : invalid 'envir' argument"

### ISSUE THREAD

**Issue by msealander** [rpremraj/mailR#39]
It seems many people get the "Error in ls(envir = envir, all.names = private) : invalid 'envir' argument" error. For me, it turned out that if my RMarkdown chunks were named with spaces in the name it spit out this error and was fixed when I replaced them with underscores.

**Comment by rpremraj** [comment]
Thanks for letting know... much appreciated.
