### ISSUE TITLE
RStudio crashing when doing summary() of glm object

### ISSUE THREAD

**Issue by abeburnett** [rpremraj/mailR#40]
This is a new one I've never seen before. I'm unable to view the summary of a glm object. Every time I do:

    summary(mdl.out)

RStudio crashes with an "R Session Aborted" error. I have no other indication of what is wrong. Any ideas what could cause this? It seems to be happening when I added a couple new variables...but neither of the variables has any apparent issues. And I can print(mdl.out) just fine, just not look at the summary. 

I'd appreciate any ideas you have on how to figure out what the heck is going on. I've tried restarting my R session and clearing out my environment and re-running everything--to no avail.

Thank you in advance!

**Comment by abeburnett** [comment]
Also, I was able to run this in R Commander just fine... In R Commander, summary(glm.obj) worked fine, as did everything else I was doing (glmulti model averaging and gbm estimation). But man I hope we can figure out what's causing RStudio to crash as working in R Commander is rough.

**Comment by abeburnett** [comment]
Okay, weird, I meant to post this to the R Studio repo. Sorry!

**Comment by rpremraj** [comment]
No worries --- I was confused though.
