### ISSUE TITLE
JavaVM: requested Java version ((null)) not available. Using Java at "" instead.

### ISSUE THREAD

**Issue by 3dmashup** [rpremraj/mailR#49]
This is from a Mac OS/X  El Capitan with the latest JDK installed. How is the location of the JVM
determined?

install.packages("mailR", dep = T)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 22  587k   22  129k    0     0   116k      0  0:00:05  0:00:01  0:00:04  116k100  587k  100  587k    0     0   351k      0  0:00:01  0:00:01 --:--:--  351k

The downloaded binary packages are in
    /var/folders/82/8m7g007j535728nss3fcskc00000gp/T//Rtmp6vv3ot/downloaded_packages

> library(mailR)
> install.packages("mailR", dep = T)
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 22  587k   22  129k    0     0   116k      0  0:00:05  0:00:01  0:00:04  116k100  587k  100  587k    0     0   351k      0  0:00:01  0:00:01 --:--:--  351k

The downloaded binary packages are in
    /var/folders/82/8m7g007j535728nss3fcskc00000gp/T//Rtmp6vv3ot/downloaded_packages

> library(mailR)
> JavaVM: requested Java version ((null)) not available. Using Java at "" instead.
> JavaVM: Failed to load JVM: /bundle/Libraries/libserver.dylib
> JavaVM FATAL: Failed to load the jvm library.
> Error : .onLoad failed in loadNamespace() for 'mailR', details:
>   call: .jinit()
>   error: JNI_GetCreatedJavaVMs returned -1

Error: package or namespace load failed for ‘mailR’

> JavaVM: Failed to load JVM: /bundle/Libraries/libserver.dylib
> JavaVM FATAL: Failed to load the jvm library.
> Error : .onLoad failed in loadNamespace() for 'mailR', details:
>   call: .jinit()
>   error: JNI_GetCreatedJavaVMs returned -1

Error: package or namespace load failed for ‘mailR’

**Comment by rpremraj** [comment]
This is not a mailR issue... looks like you have trouble with your Java installation.
