### ISSUE TITLE
loading library 

### ISSUE THREAD

**Issue by ghost** [rpremraj/mailR#52]
I am using R 3.2.3, and when I try to install I get the following output.  Thanks for your help in troubleshooting.

 library(mailR)
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dirname(this$RuntimeLib)
  error: a character vector argument expected
In addition: Warning message:
package ‘mailR’ was built under R version 3.2.5 
Error: package or namespace load failed for ‘mailR’

**Comment by jgiacomo** [comment]
Make sure you have Java installed on your system. It is a requirement of the rJava package, see the CRAN package site https://cran.r-project.org/web/packages/rJava/index.html

**Comment by rpremraj** [comment]
This is a rJava related issue. Please refer to their documentation.
