### ISSUE TITLE
Segementation Fault during MailR install

### ISSUE THREAD

**Issue by jeganathan-velu** [rpremraj/mailR#65]
Hi,

We are facing the below issue, during mailR installation from CRAN and also during installation via github. Could not find any reference in Stackoverflow too. Tried reinstalling rJava and stringr/stringi packages, still could not get it installed. It is running fine in our other ubuntu servers (14.04). Any help will be much appreciated. Thanks in advance.

* installing *source* package ‘mailR’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Segmentation fault (core dumped)
ERROR: loading failed
* removing ‘/home/usr/R/x86_64-pc-linux-gnu-library/3.3/mailR’
Error: Command failed (1)

**Comment by JesseYANK** [comment]
installing source package ‘mailR’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Segmentation fault (core dumped)
ERROR: loading failed

I also got segmentation fault error.

**Comment by rpremraj** [comment]
Thanks for reporting this in. I will try reproducing the error at my end and give you feedback.

@JesseYANK Which version of R are you using?

**Comment by JesseYANK** [comment]
@rpremraj R version 3.4.0(2017-04-21)
Linux 4.4.0-81-generic x86_64

Thanks for your prompt response

**Comment by rpremraj** [comment]
Sorry, so far the package compiles successfully on my [windows] machine. Will update the java libraries so you can see whether it helps.

**Comment by joel23888** [comment]
I am having the same issue, see #61

**Comment by joel23888** [comment]
I managed to find a solution to this at: https://stackoverflow.com/questions/44682540/rjava-dependent-package-installation-segmentation-fault-core-dumped. Closed #61 and probably this can issue can be close if works for those who posted here. Hope this helps.

**Comment by rpremraj** [comment]
Thanks for the link @joel23888. Glad you worked it out.

There is seemingly more info here: https://github.com/s-u/rJava/issues/110.
