### ISSUE TITLE
how to set recipientsDisplayName

### ISSUE THREAD

**Issue by zhouq1986** [rpremraj/mailR#72]
I use mailR to send Email, code like this:
send.mail(  
  from = "dsdsjzx@thfund.com.cn" ,  
  to = "zhouq@thfund.com.cn",  
  subject = "this is title" ,  
  body = body,  
  encoding = "utf-8",  
  html = TRUE,  
  smtp = list(  
    host.name = "mailtj.thfund.com.cn",  
    port = 25,  
    user.name = "dsdsjzx@thfund.com.cn" ,  
    passwd = "****"
  ),  
  authenticate = FALSE,  
  send = TRUE  
)  
but I want to set recipientsDisplayName , like "电商大数据中心"
In C#, the have recipientsDisplayName . like 
_### string recipientsDisplayName = "张三";//这个配置的是收件人的要显示在邮件的名称   
MailAddress mailfrom = new MailAddress(from, senderDisplayName, encoding);//发件人邮箱地址，名称，编码UTF8_   

 how to use mailR  to do this?

**Comment by rpremraj** [comment]
You can accomplish this presented in the first example in the Readme file:
```r
send.mail(from = "Sender Name <sender@gmail.com>",
          to = c("Recipient Name 1 <recipient1@gmail.com>", "Recipience Name 2 <recipient2@gmail.com>"),
          subject = "Subject of the email",
          body = "Body of the email",
          smtp = list(host.name = "aspmx.l.google.com", port = 25),
          authenticate = FALSE,
          send = TRUE)
```
